require:
- rubocop-minitest
- rubocop-sorbet

AllCops:
  TargetRubyVersion: 3.1
  NewCops: disable

Lint/UselessMethodDefinition:
  Exclude:
    - 'templates/*.rb'

Metrics/MethodLength:
  Max: 15

Style/StringLiterals:
  EnforcedStyle: 'double_quotes'
