# DO NOT EDIT MANUALLY
# This is an autogenerated file for unresolved constants.
# Please instead update this file by running `bin/tapioca todo`.

# typed: false

module Rack::Request::Env; end
module Rack::Request::Helpers; end
module Regexp::Expression::Subexpression; end
module RuboCop::AST::Node; end
module RuboCop::AST::NodePattern; end
module RuboCop::AST::NodePattern::Macros; end
module RuboCop::AST::Sexp; end
module RuboCop::AST::Token; end
module RuboCop::AST::Traversal; end
